### ISSUE TITLE
Enhance extension implementation

### ISSUE THREAD

**Issue by Procyon-b** [dutiyesh/off-the-record-history#1] opened 2019-10-18 14:25 UTC
I've played a bit with the code of the current version (0.1.4), and I can propose enhancements.

These enhancement consist in:
- getting rid of the content script. Logging tabs events can be done directly from the background page.
- using local storage, and constantly parsing+stringifing the whole log is not necessary since we don't need to keep the history from one session to another. A popup window can read background page's variables. Cleaning is not even necessary (not talking about the clear button) since the extension works in split mode and all its datas are lost when the last incognito tab is closed.

I can post the revised code when you're ready.   ;)

**Edit:**
In fact the local storage is used only if the background page is not persistent, but I have found a way to access the storage only when needed.

**Comment by dutiyesh** [comment] 2019-10-19 04:36
> getting rid of the content script. Logging tabs events can be done directly from the background page.

Yeah, we can do that.


> A popup window can read background page's variables. Cleaning is not even necessary (not talking about the clear button) since the extension works in split mode and all its datas are lost when the last incognito tab is closed.

I think we still have to clear the variable's value. Because background page will maintain it even when all tabs are closed (at least until it is not unloaded).


> In fact the local storage is used only if the background page is not persistent, but I have found a way to access the storage only when needed.

How?

**Comment by Procyon-b** [comment] 2019-10-19 13:37
I'm currently running my modified code. And it seems to work as expected.

**content script/background**
In the background page I use `chrome.tabs.onUpdated.addListener` which is called several times for the same tab (but the trick I use makes it easy to fill the infos gradually).

**clear variables**
When an extension works in split mode it has 2 identical background pages. The specificity of the incognito version is that, once all the incognito tabs/windows are closed (including developper console), the background page is closed and all its datas are discarded. Even local storage.

**local storage**
Since the background is not persistent, when it is unloaded variable are lost. (_I only played with persistent ones myself_). So I set it to store its variables with `chrome.runtime.onSuspend.addListener`. And the background script automatically loads it at restart with
`var tabs = JSON.parse(localStorage.incHist || '{}')`

The last thing was to wake up the background page from the popup window. Just an async call. And while the popup is opened, the bg isn't unloaded.


I don't see the source code here. Instead of a PR  I'll post a zip file of the extension later. I still have to clean comments and console logging.

**Comment by Procyon-b** [comment] 2019-10-22 17:15
[OTR.0.1.4.1.zip](https://github.com/dutiyesh/off-the-record-history/files/3757218/OTR.0.1.4.1.zip)

What has been modified:
- I've added default-favicon.ico as a local file. It prevents unecessary connection to a distant server.
- I've left the link to google analytics, but be aware that uBlock Origin blocks access to this url.
- userscript deleted and reference in manifest removed.
- `chrome.extension.inIncognitoContext` is used to detect incognito tab/window.
The first thing the background page does is detect this, and unloads if in standard mode.
Detection in the popup window is simplified. No more async call to `tabs.query()`
- the popup wakes up the background script if necessary with an async call `chrome.runtime.getBackgroundPage(init);` . That's why `init()` is not an anymous function anymore in `document.addEventListener()`
- the popup is using direct references to bg vars. While the popup stays open, chrome keeps the bg loaded.

- the background script uses `chrome.tabs.onUpdated.addListener` to keep track of tabs events. Tab info is stored in `tabs={}` with their id as the key. The object is also pushed in the history array (at that point, `tabs` and `incHist` are linking to the same object, up until the time when the background script is suspended). Several events are used to fill in the complete info: title and favicon info come later.
- `chrome.runtime.onSuspend.addListener()` is used to store vars when the script is "suspended".
- `chrome.tabs.onReplaced.addListener()` has been added to catch chrome modifying tabs id. Something I found while helping debugging someone else's extension.

**Comment by dutiyesh** [comment] 2019-10-22 18:17
@Procyon-b I have open sourced the extension code in this repository, could you send a pull request with above changes?

**Comment by Procyon-b** [comment] 2019-10-22 18:34
No problem  :)

**Comment by dutiyesh** [comment] 2019-10-22 18:34
Awesome!

**Comment by Procyon-b** [comment] 2019-10-22 19:01
Tell me if you have any problem while running it.
I've taken a couple days to foolproof all the modifications, but bugs are still possible.  ;)

**Comment by yu91755** [comment] 2020-02-09 10:30
Duplicate of #

**Closed as completed** 2020-08-29 11:42 UTC
Labels: enhancement
